console.log("Hello World")
console.log('i am learning javascript')
console.log(10*80)



// console.log(x-y)
// console.log(x*y)
// console.log(x/y)
// console.log(x%y)

// let x=5
// x++ // 6
// ++x // 7
// --x // 6
// x-- // 5
// x++ // 6
// x-- // 7
// console.log(x++) // 7
// console.log(--x) // 7
// 7,7
// 5, 3

// >, >=, <, <=, ==, !==,===, !==

let a = 10;
let b = 20;

console.log(a<b)
console.log(a>b)
console.log(a<=b)
console.log(a>=b)
console.log(a===b)