const schoolname = "ROOTS"
// console.log(schoolname [4])
// console.log(schoolname [3])
// console.log(schoolname [2])
// console.log(schoolname [1])
// console.log(schoolname [0])

// for (let i = 0; i < schoolname.length; i++) {
//     console.log(schoolname[i])
// }

// for(let i = schoolname.length - 1; i >= 0; i--){
//     console.log(schoolname[i])
// }

// let text = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
// let length = text.length;

// console.log(length)

// let text = "HELLO WORLD";
// let char = text.charAt(0);
// console.log(length)

// let text = "HELLO WORLD";
// let char = text.charcodeat(0);





